name: Secure CI/CD Pipeline

on: [push, pull_request]

permissions:
  contents: read
  security-events: write

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests (placeholder)
        run: echo "Tests passed!"

      # run bandit via pre-commit (configured below)
      - name: Run pre-commit (Bandit included)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - name: Build Docker image
        run: docker build -t secure-app .

      # pin trivy to a stable tag and upload SARIF
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: secure-app
          format: sarif
          output: trivy-results.sarif
          # optional hardening:
          # vuln-type: 'os,library'
          # severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
